-- Catalog IDs correspond to the 58 products inserted by 01-schema.sql.
-- Files are served from Astro's public/img directory, not remote image hosts.
USE freshexpress_operacional;
UPDATE empresas SET logo = CASE id
  WHEN 1 THEN '/img/empresas/fruites-can-pep.svg'
  WHEN 2 THEN '/img/empresas/verdures-la-masia.svg'
  WHEN 3 THEN '/img/empresas/carnisseria-el-bou.svg'
  WHEN 4 THEN '/img/empresas/peixateria-mar-blau.svg'
  WHEN 5 THEN '/img/empresas/lactis-la-granja.svg'
  WHEN 6 THEN '/img/empresas/forn-de-pa-el-moli.svg'
END WHERE id BETWEEN 1 AND 6;
UPDATE productos SET imagen = CASE id
  WHEN 1 THEN '/img/productos/pomes.jpg'
  WHEN 2 THEN '/img/productos/taronges.jpg'
  WHEN 3 THEN '/img/productos/platans.jpg'
  WHEN 4 THEN '/img/productos/maduixes.jpg'
  WHEN 5 THEN '/img/productos/kiwis.jpg'
  WHEN 6 THEN '/img/productos/peres.jpg'
  WHEN 7 THEN '/img/productos/raim.jpg'
  WHEN 8 THEN '/img/productos/melo.jpg'
  WHEN 9 THEN '/img/productos/sindria.jpg'
  WHEN 10 THEN '/img/productos/mangos.jpg'
  WHEN 11 THEN '/img/productos/tomaquets-penjar.jpg'
  WHEN 12 THEN '/img/productos/enciams.jpg'
  WHEN 13 THEN '/img/productos/cebes.jpg'
  WHEN 14 THEN '/img/productos/alls.jpg'
  WHEN 15 THEN '/img/productos/patates.jpg'
  WHEN 16 THEN '/img/productos/pastanagues.jpg'
  WHEN 17 THEN '/img/productos/carabasses.jpg'
  WHEN 18 THEN '/img/productos/alberginies.jpg'
  WHEN 19 THEN '/img/productos/pebrots.jpg'
  WHEN 20 THEN '/img/productos/carbassons.jpg'
  WHEN 21 THEN '/img/productos/espinacs.jpg'
  WHEN 22 THEN '/img/productos/broquil.jpg'
  WHEN 23 THEN '/img/productos/vedella.jpg'
  WHEN 24 THEN '/img/productos/costelles-porc.jpg'
  WHEN 25 THEN '/img/productos/pit-pollastre.jpg'
  WHEN 26 THEN '/img/productos/cuixes-pollastre.jpg'
  WHEN 27 THEN '/img/productos/hamburgueses.jpg'
  WHEN 28 THEN '/img/productos/llom-porc.jpg'
  WHEN 29 THEN '/img/productos/botifarra.jpg'
  WHEN 30 THEN '/img/productos/xorico.jpg'
  WHEN 31 THEN '/img/productos/pernil.jpg'
  WHEN 32 THEN '/img/productos/carn-picada.jpg'
  WHEN 33 THEN '/img/productos/salmo.jpg'
  WHEN 34 THEN '/img/productos/gambes.jpg'
  WHEN 35 THEN '/img/productos/llobarro.jpg'
  WHEN 36 THEN '/img/productos/musclos.jpg'
  WHEN 37 THEN '/img/productos/cloisses.jpg'
  WHEN 38 THEN '/img/productos/tonyina.jpg'
  WHEN 39 THEN '/img/productos/sardines.jpg'
  WHEN 40 THEN '/img/productos/calamars.jpg'
  WHEN 41 THEN '/img/productos/rap.jpg'
  WHEN 42 THEN '/img/productos/bacalla.jpg'
  WHEN 43 THEN '/img/productos/llet.jpg'
  WHEN 44 THEN '/img/productos/iogurt.jpg'
  WHEN 45 THEN '/img/productos/formatge-fresc.jpg'
  WHEN 46 THEN '/img/productos/formatge-curat.jpg'
  WHEN 47 THEN '/img/productos/mantega.jpg'
  WHEN 48 THEN '/img/productos/nata.jpg'
  WHEN 49 THEN '/img/productos/mato.jpg'
  WHEN 50 THEN '/img/productos/ous.jpg'
  WHEN 51 THEN '/img/productos/pa-pages.jpg'
  WHEN 52 THEN '/img/productos/baguette.jpg'
  WHEN 53 THEN '/img/productos/pa-integral.jpg'
  WHEN 54 THEN '/img/productos/croissant.jpg'
  WHEN 55 THEN '/img/productos/ensaimades.jpg'
  WHEN 56 THEN '/img/productos/coca-vidre.jpg'
  WHEN 57 THEN '/img/productos/pa-motlle.jpg'
  WHEN 58 THEN '/img/productos/magdalenes.jpg'
END WHERE id BETWEEN 1 AND 58;
